[package]
name = "rollup-executor"
version = "0.1.0"
edition = "2024"

[dependencies]
# sp1 = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
merkletree = "0.22"
tokio = { version = "1", features = ["full"] }