[package]
name = "program"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-program = "1.18.0"
# sp1 = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
borsh = "0.10"
borsh-derive = "0.10"

[lib]
crate-type = ["cdylib", "lib"]